version: '3.8'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgres/data
      - ./migrations/:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    restart: on-failure:5
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: